set hivevar:HIVEMODEL_NAME=${HIVE_EXCHANGE_MODEL1};
set hivevar:SAS_SCORES_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME};
set hivevar:SCORES_IMP_LTST_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_ltst;
set hivevar:SCORES_IMP_REPOS_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_repos;
set hivevar:SCORES_EXP_LTST_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_export_ltst;
set hivevar:SCORES_EXP_REPOS_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_export_repos;
 