set hivevar:HIVEMODEL_NAME=${HIVE_MODEL3};
set hivevar:SAS_SCORES_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_scores;
set hivevar:SCORES_IMP_LTST_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_scores_ltst;
set hivevar:SCORES_IMP_REPOS_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_scores_repos;
set hivevar:SCORES_EXP_LTST_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_scores_export_ltst;
set hivevar:SCORES_EXP_REPOS_TABLE=${HIVEFUNCTION_GROUP}_${HIVEMODEL_NAME}_scores_export_repos;
